<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Добавить' => ' Add',
    'Код может содержать только буквы a-z, - и _' => 'Code can contain only a-z letters, - and _',
    'Url' => 'Url',
    'Атрибут url' => 'Url attribute',
    'Атрибут заголовка' => 'Title attribute',
    'Атрибут описания' => 'Description attribute',
    'Вы действительно хотите удалить меню?' => 'Do you really want to delete the menu?',
    'Далее' => 'Next',
    'Добавить новое меню' => 'Add new menu',
    'Добавить пункт меню' => 'Add menu item',
    'Из модели' => 'From model',
    'Класс иконки' => 'Icon className',
    'Класс модели' => 'Model class',
    'Код' => 'Code',
    'Меню' => 'Menu',
    'Меню не найдено' => 'Menu is not found',
    'Меню успешно обновлено' => 'Menu updated successfully',
    'Назад' => 'Back',
    'Название' => 'Title',
    'Новое меню' => 'New menu',
    'Новый пункт меню' => 'New menu item',
    'Описание' => 'Description',
    'Отмена' => 'Cancel',
    'Ошибка валидации' => 'Validation error',
    'Ошибка данных' => 'Data error',
    'Ошибка добавления меню' => 'Menu adding error',
    'Ошибка сохранения элемента ' => 'Menu item saving error',
    'Параметры выборки (where, order by)' => 'Selection parameters (where, order by)',
    'При обновлении меню произошла ошибка' => 'An error occurred while updating the menu',
    'При обновлении пунктов меню произошла ошибка:' => 'An error occurred when updating menu items:',
    'Простая ссылка' => 'Simple link',
    'Редактирование меню: ' => 'Menu edit: ',
    'Редактировать' => 'Edit',
    'Сохранить' => 'Save',
    'Список ссылок берется из записей модели' => 'The list of links is taken from the model records',
    'Ссылка указывается вручную' => 'The link is specified manually',
    'Тип' => 'Type',
    'Тип элемента меню' => 'Menu element type',
    'Удалить' => 'Delete',
    'Удалить меню' => 'Delete menu',
    'Удалить пункт меню и его дочерние пункты?' => 'Delete a menu item and its child items?',
    'атрибут_url' => 'url_attribute',
];
