<?php
namespace mix8872\menu\assets;

use Yii;

class MenuAsset extends \yii\web\AssetBundle
{
    public function init()
    {
        if (isset(Yii::$app->params['bsVersion']) && Yii::$app->params['bsVersion'] === '4.x') {
            $this->css = [
                'css/menu-bs4.css',
            ];
            $this->depends = [
                ToastAsset::class,
                'rmrevin\yii\fontawesome\AssetBundle',
                '\yii\bootstrap4\BootstrapPluginAsset'
            ];
        } else {
            $this->css = [
                'css/menu-bs3.css',
            ];
            $this->depends = [
                ToastAsset::class,
                'rmrevin\yii\fontawesome\AssetBundle',
                '\yii\bootstrap\BootstrapPluginAsset'
            ];
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    public $sourcePath = '@mix8872/menu/assets';
}
